### PR TITLE
Use shallow clone for packer | set bg colour | Fix visual selection color | Misc improvements

### PR DESCRIPTION
**Pull request by Akianonymus**

### CODE REVIEW

**Comment by Akianonymus** [comment]
> grey looks ok for comment , whats wrong with it?

It's not about looking ok, when a block of code is selected, then the comments are not visible.

So, i changed the comment color, or you have to use seperate colour for visual selection.

```
:hi Visual guibg=some_color
```

Didn't do this as it's fixed with the new colour, and it isn't much deviated from original.

**Comment by Akianonymus** [comment]
> > > grey looks ok for comment , whats wrong with it?
> > 
> > 
> > It's not about looking ok, when a block of code is selected, then the comments are not visible.
> > So, i changed the comment color, or you have to use seperate colour for visual selection.
> > ```
> > :hi Visual guibg=some_color
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Didn't do this as it's fixed with the new colour, and it isn't much deviated from original.
> 
> does this looks ok?
> 
> image

Can you send a big screenshot with big selection ? or the color code
Not much visible

In the end, it should be easy on the eyes, no matter what colour it is.

**Comment by siduck76** [comment]
> > > > grey looks ok for comment , whats wrong with it?
> > > 
> > > 
> > > It's not about looking ok, when a block of code is selected, then the comments are not visible.
> > > So, i changed the comment color, or you have to use seperate colour for visual selection.
> > > ```
> > > :hi Visual guibg=some_color
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Didn't do this as it's fixed with the new colour, and it isn't much deviated from original.
> > 
> > 
> > does this looks ok?
> > image
> 
> Can you send a big screenshot with big selection ? or the color code
> Not much visible
> 
> In the end, it should be easy on the eyes, no matter what colour it is.

try it yourself , add

 bg("Visual", one_bg)

**Comment by Akianonymus** [comment]
> > > > > grey looks ok for comment , whats wrong with it?
> > > > 
> > > > 
> > > > It's not about looking ok, when a block of code is selected, then the comments are not visible.
> > > > So, i changed the comment color, or you have to use seperate colour for visual selection.
> > > > ```
> > > > :hi Visual guibg=some_color
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Didn't do this as it's fixed with the new colour, and it isn't much deviated from original.
> > > 
> > > 
> > > does this looks ok?
> > > image
> > 
> > 
> > Can you send a big screenshot with big selection ? or the color code
> > Not much visible
> > In the end, it should be easy on the eyes, no matter what colour it is.
> 
> try it yourself , add
> 
> bg("Visual", one_bg)

I think it's too dim, not visible enough.

My changes
Screenshot_20210713-190

Your Changes
Screenshot_202107

**Review by siduck76 — APPROVED** [review]

**Pull request merged**
