### PR TITLE
Fix default mappings not load if chadrc.lua does not exist

### LINKED ISSUE #1961: Error executing vim.schedule lua callback
Error executing vim.schedule lua callback: /home/sabi/.config/nvim/lua/core/utils.lua:80: attempt to index a nil value                                         
stack traceback:                                                                                                                                               
        /home/sabi/.config/nvim/lua/core/utils.lua:80: in function </home/sabi/.config/nvim/lua/core/utils.lua:55>

I had installed NvChad and removed if by  `rm ~/.config/nvim`

Now when I tried to reinstall again, it gives me this error. Whenever I open with NvChad config this error comes

image

### PR DESCRIPTION
**Pull request by azuwis**
The regression was introduced by dab9171e6426b6eb8f0f8bcd0829a0415d260fcb

Fix #1961 #2025

### CODE REVIEW

**Comment by azuwis** [comment]
@siduck Can you please have a look at this, `config.mappings` is an empty map if chadrc.lua not exist.

**Comment by siduck** [comment]
> The regression was introduced by [dab9171](https://github.com/NvChad/NvChad/commit/dab9171e6426b6eb8f0f8bcd0829a0415d260fcb)
> 
> Fix #1961 #2025

those errors get fixed when we delete the old nvim dir, it usually happens when you dont delete old nvim dir ( .local/share/nvim ) before installing nvchad

**Comment by azuwis** [comment]
The steps to reproduce is simple:

```
$ rm ~/.config/nvim/lua/custom/chadrc.lua
$ nvim
```

Before dab9171, it's fine because default mapping is loaded in `default_config.lua` (`M.mappings = require "core.mappings"`).

The ability to run NvChad without `chadrc.lua` is necessary for packaging for Linux dist.

I was trying to [package NvChad for NixOS](https://github.com/azuwis/nix-config/blob/master/modules/home/nvchad/default.nix), and found the problem.

**Comment by siduck** [comment]
> The ability to run NvChad without chadrc.lua is necessary for packaging for Linux dist.

you're right. I before removed that code cuz i assumed everyone would have the chadrc by default, because during the installation,  it'll prompt you to bootstrap example_config, if you select no to it, then it'll still create a custom chadrc

**Review by siduck — APPROVED** [review]

**Pull request merged**
