### PR TITLE
added more badges

### PR DESCRIPTION
**Pull request by ashincoder**
added badges

- Stars
- Issues

### CODE REVIEW

**Comment by siduck76** [comment]
@ashincoder can we have flat badges? something like these

image

**Comment by siduck76** [comment]
also let me know if its possible to have a badge like this 
image

I want to add the neovim logo instead :D

**Comment by ashincoder** [comment]
Yeah I will see


> also let me know if its possible to have a badge like this
> image
> 
> I want to add the neovim logo instead :D

I will look into it.

**Comment by ashincoder** [comment]
ok

**Comment by ashincoder** [comment]
Full clear. 

> also let me know if its possible to have a badge like this
> image
> 
> I want to add the neovim logo instead :D

I will take a look at it later.

**Comment by ashincoder** [comment]
To see the effect take a look at here https://github.com/ashincoder/NvChad

**Comment by siduck76** [comment]
@ashincoder can you center the badges?

**Comment by siduck76** [comment]
also can we change the fg color in this light colored badges?
 like  black fg in green , yellow badges
image

**Comment by ashincoder** [comment]
@siduck76 could you change the colors. Cause your taste may be better. Mine's shit :cry:

**Pull request merged**
