### PR TITLE
Added lazy loaded which key plugin

### PR DESCRIPTION
**Pull request by ashincoder**

### CODE REVIEW

**Comment by siduck76** [comment]
ehhh not yet! I need to check whichkey configuring first , it gets hard for me if someone sends PR of something which I dont know.

**Comment by siduck76** [comment]
So keep this PR opened for a while , I'll check whichkey next month.

**Comment by ashincoder** [comment]
What about which key confuses you

**Comment by siduck76** [comment]
> What about which key confuses you

its not about confusing , Im just now familiar with it much . I'll check its docs soon

**Pull request closed without merging**
