### PR TITLE
WIP v2.0 GigaChad release

### PR DESCRIPTION
**Pull request by siduck**
https://github.com/orgs/NvChad/projects/8

Other pr's related to this release

https://github.com/NvChad/ui/pull/36
https://github.com/NvChad/base46/pull/135

Rewrite whole site in solidjs + vite, remove docusaurus cuz its a lil slow and bloated 

https://github.com/NvChad/nvchad.github.io/pull/118

### CODE REVIEW

**Comment by baoyachi** [comment]
I look forward to new version published.

**Comment by siduck** [comment]
> I look forward to new version published.

my fingers are injured at the moment so this release will be released in december

**Comment by crenshawda** [comment]
I hope your fingers are healing up, that's a really crappy injury to have, especially for developer! Thanks this all your work on this awesome project. 

Is there any thought of looking at folke's new Lazy package manager? Looks like it provides what the combination of Packer+Impatient does and requires less explicit ordering. 

https://github.com/folke/lazy.nvim

No worries if not, just felt like it was in line with NVChad's aesthetics and goals.

**Comment by siduck** [comment]
yes i will add it in the next release (only after testing it locally)

and it wont be a big breaking change because our table structure for plugins will still be the same, we just need to remember new lazy.nvim command names!  

Also v2.0 will be on a separate branch so users can take their own time in migrating to lazy.nvim

**Pull request closed without merging**
