### PR TITLE
performance: avoid reloading config

### PR DESCRIPTION
**Pull request by georgejean**
Each times `require("core.utils").load_config` is called, custom chadrc and custom mappings are merged with the default.
In particular, each call triggers the function `remove_disabled_keys` which merges the mappings.
I think it's not always necessary (excepting in the autocommand in `core.init.lua` which reloads some chadrc options on save), but maybe I'm wrong.
I propose these changes to solve this problem (use config as a property, not a method). The `config` property could perhaps be used in the `ui` repo too.
Below is a test which shows the number of calls before and after the changes.
## Before :
nvchad_load_config1

## After :
nvchad_load_config2

_Note_: I've also added a test to avoid the case where the chadrc file was created but is empty (nil).

### CODE REVIEW

**Comment by siduck** [comment]
@georgejean  you should change it at many other places too i.e our plugins (ui & base46)

image

**Comment by georgejean** [comment]
Ok, I will change it and do some testing before making PR at these repos.

**Comment by siduck** [comment]
> Ok, I will change it and do some testing before making PR at these repos.

no worries, i'll do it tomorrow!

**Comment by siduck** [comment]
ig its better to add this feature from v3.0 :D

**Comment by lucario387** [comment]
This makes it so the au in `core/init.lua` doesn't work anymore :thinking: 

I won't fix it :_p:

**Comment by siduck** [comment]
> This makes it so the au in `core/init.lua` doesn't work anymore 🤔
> 
> I won't fix it :_p:

@lucario387 its just in testing so chill, I will not merge it into main unless it works 100% at all places

**Pull request merged**
