### PR TITLE
Add tomorrow-night theme

### PR DESCRIPTION
**Pull request by alternateved**
Custom Tomorrow Night theme made from Tomorrow Night and Tomorrow Night Bright base16 themes. 
image

### CODE REVIEW

**Comment by siduck76** [comment]
@alternateved gruvchad theme is already in WIP , I'll finish that theme in some days . Sorry but this PR might delay for like 4-5 days.

**Comment by siduck76** [comment]
@alternateved is there any xresources theme for tomorrow night?

**Comment by alternateved** [comment]
How about [this](https://github.com/chriskempson/tomorrow-theme/blob/master/Xdefaults/XresourceTomorrowNight)?

**Comment by siduck76** [comment]
> @siduck76 how about [this](https://github.com/chriskempson/tomorrow-theme/blob/master/Xdefaults/XresourceTomorrowNight)?

looks neat , I'll test it tomorrow btw tokyonight == tomorrowNight?

**Comment by alternateved** [comment]
Nah, tokyonight is totally different. Tomorrow Night is more chill, while tokyonight is more neon-y. Btw, Tomorrow Night is the theme made by author of [base16](https://github.com/chriskempson/base16).

**Comment by siduck76** [comment]
could you show how it looks on nvchad?

**Comment by alternateved** [comment]
It is funny, cause I already did. I guess the difference in colors is quite subtke, since the theme is based on base16.  

image

**Comment by siduck76** [comment]
> It is funny, cause I already did. I guess the difference in colors is quite subtke, since the theme is based on base16.
> 
> image

oh lol I meant another screenshot ,  like show another file ( lspconfig.lua)

image

**Comment by alternateved** [comment]
How about this picture?
image

**Comment by siduck76** [comment]
looks ok , btw you the darker_black is too dark , can you change it to #131517 ?

**Comment by siduck76** [comment]
Ive made a lil tool to lighten darken hex colors 

image

**Comment by siduck76** [comment]
show me how lspconfig.lua file looks , it has many colors so could be easy to tell how good does tomorrow-night look :p

**Comment by alternateved** [comment]
Sure, this is end result of that change - I hope it is enough to see the colors, even though my lspconfig.lua is quite different:

image

**Comment by siduck76** [comment]
nice , great job! I thought I made the theme making process too hard since we need to use colors that match everything and follow highlights.lua.

**Comment by alternateved** [comment]
In the beginning I was kinda lost, but after a little practice it wasn't so hard anymore. Maybe it would be a bit easier if color names would be more meaningful.

**Comment by siduck76** [comment]
> In the beginning I was kinda lost, but after a little practice it wasn't so hard anymore. Maybe it would be a bit easier if color names would be more meaningful.

I did consider using better color names before but since the same color is used for multiple highlights so I dropped that idea , anyways the wiki might make it simple https://github.com/siduck76/NvChad/wiki#submitting-your-own-themes

**Comment by siduck76** [comment]
Btw you kept some colors unchanged like grey etc , I'll change them eventually 

before , after 

image

**Comment by alternateved** [comment]
Ah, yes, you are right. For one thing, it may be caused by difference in terminal emulators. As you can see in my screenshots, my bufferline looks totally different. For other thing, I didn't really have any idea what to do with that `purple` color:
image

**Comment by siduck76** [comment]
> Ah, yes, you are right. For one thing, it may be caused by difference in terminal emulators. As you can see in my screenshots, my bufferline looks totally different. For other thing, I didn't really have any idea what to do with that `purple` color:
> image

no worries I'll fix those soon.

**Comment by alternateved** [comment]
Btw, I did change `grey` color, but I guess this change wasn't good enough for this theme. Could you kindly tell me, how did you find grey which works so well in this theme?

**Comment by siduck76** [comment]
> Btw, I did change `grey` color, but I guess this change wasn't good enough for this theme. Could you kindly tell me, how did you find grey which works so well in this theme?

To make a great theme you just need to use lighter/darker shades of the main color , In tomorrow-night's colorscheme we have #1d1f21 as bg color and the grey color we're using is used for comments , line numbers etc so it should be dimmed version of the main bg color , i just lightened the color with my tool 

image

**Comment by alternateved** [comment]
I see. Really good idea. Thank you for answering that.

**Pull request merged**
