### PR TITLE
added option to select languages from treesitter config and smart indent

### PR DESCRIPTION
**Pull request by ashincoder**
Hello I added the following things:

- To select languages from the treesitter config
- Treesitter based indentation
- Option for smart indentation was added in init.lua

### CODE REVIEW

**Comment by siduck76** [comment]
@ashincoder did you try the treesitter indenting? It didnt work well for me the last time

**Comment by ashincoder** [comment]
It did work when i tested

**Comment by ashincoder** [comment]
Did it work

**Comment by siduck76** [comment]
@ashincoder add this in misc-utils.lua file `opt("b", "smartindent", true)`

This worked without adding indent in treesitter

**Comment by ashincoder** [comment]
Ok. Will do now

**Comment by ashincoder** [comment]
Should I remove treesitter indentation

**Comment by siduck76** [comment]
> Should I remove treesitter indentation

close this PR , I'll add the smartindent

**Comment by ashincoder** [comment]
ok @siduck76

**Pull request closed without merging**
