### PR TITLE
Color settings

### PR DESCRIPTION
**Pull request by alternateved**
Clean up colorsheme-related stuff from `init.lua` and move it to separate file in `nvim/lua` folder.

### CODE REVIEW

**Review by ashincoder — CHANGES_REQUESTED** [review]
maybe remove the cmd syntax on since it works without it and also it causes a delay in loading nvim

**Comment by alternateved** [comment]
Right. The modification is done now.

**Comment by siduck76** [comment]
@alternateved The init.lua's already very short , adding those 4-5 lines to a separate file would make the config look bigger. Also the theme is an important part of the config so I put it in the init.lua file , whenever we open the ~/.config/nvim config folder its init.lua can accessed directly unlike colors.lua which is in the lua folder ( using nvimtree for this might take more time than just opening init.lua)

**Comment by ashincoder** [comment]
@siduck76 if we add `require "colors"` at the top of the document it will be loaded first. So no big deal

**Comment by ashincoder** [comment]
Adding different files in the lua directory is more better right. Seperate config for seperate purpose.
**Unix Philosopy**

**Comment by alternateved** [comment]
I guess it is a matter of preference. I prefer to have my `init.lua` file just for initiating everything else. Like this:
image

It is much more comfortable for me to just edit the file which contains specific functionality.

**Comment by ashincoder** [comment]
yeah me too. That is the name of the file init.lua

**Comment by siduck76** [comment]
> @siduck76 if we add `require "colors"` at the top of the document it will be loaded first. So no big deal

the order cant change , some plugins are loaded before the highlights etc , we might need to load certain plugins after it and its a big hassle lol so I kept it that way :p

**Comment by siduck76** [comment]
Also the init.lua looking that empty doesnt look so right to me , yes ik this is very biased lol. I'll try to keep files as less as possible in nvchad and since init.lua isnt more than 100+ lines we'll define the theme in it.

**Pull request closed without merging**
