### PR TITLE
added special telescope mapping for neovim config files

### PR DESCRIPTION
**Pull request by ashincoder**
added special telescope mapping for neovim config files
SPC f l

### CODE REVIEW

**Comment by siduck76** [comment]
@ashincoder this works very well , And @Vanderscycle you dont need to make the PR anymore

**Comment by siduck76** [comment]
btw can @ashincoder can we cd in the ~/.config/nvim folder via telescope too? if we would get this warning since the default cwd is home
 
image

**Comment by ashincoder** [comment]
Oh I check it

**Comment by ashincoder** [comment]
I don't think we can.
Users may prefer ~/

**Comment by siduck76** [comment]
> I don't think we can.
> Users may prefer ~/

cd ~/.config/nvim/ | Telescope find_files cwd=~/.config/nvim

**Comment by siduck76** [comment]
If we open nvim tree ( and it shows the home folder contents ) then it will not matter even if we did cd to any folder , nvimtree wont update its content. but if we didnt open nvimtree and cd into any folder , the nvimtree will update its content itself.
https://user-images.githubusercontent.com/59060246/124499267-5e069c80-dddb-11eb-8d2a-970dfd92c9cc.mp4

**Comment by ashincoder** [comment]
yeah it works

**Comment by ashincoder** [comment]
Shall I do a PR

**Comment by siduck76** [comment]
> Shall I do a PR

no wait , we'll wait till this thing gets fixed https://github.com/kyazdani42/nvim-tree.lua/issues/489

**Comment by ashincoder** [comment]
OK

**Comment by siduck76** [comment]
> OK

no need to close it , re-open it if you can.

**Comment by ashincoder** [comment]
Hello I dont't think the command I wrote was good, cause when I use which key it show's the whole command.

**Comment by ashincoder** [comment]
check this https://github.com/folke/which-key.nvim/issues/119. I think we can use which key

**Pull request closed without merging**
