### PR TITLE
Add developer plugins & settings

### PR DESCRIPTION
**Pull request by jtuz**

### CODE REVIEW

**Comment by siduck76** [comment]
why vim polygot? we already have treesitter

**Comment by siduck76** [comment]
indicator icon would make the tabs look bad , Im fine with not having it

**Comment by ashincoder** [comment]
These settings looks like an overkill

**Comment by siduck76** [comment]
@jtuz if some stuffs dont work with whichkey for you , mention them and give proper configs so I will at least put them in wiki so people facing same issue as yours will be helped too :)

**Pull request closed without merging**
