### PR TITLE
Added .gitignore and lazy load lsp_signature more

### PR DESCRIPTION
**Pull request by ashincoder**

### CODE REVIEW

**Comment by ashincoder** [comment]
I have made lsp_signature to load during insert cause it is mainly used for showing the insertable functions instead of loading it after lsp_config

**Comment by siduck76** [comment]
@ashincoder you should test it before sending PR , lspsignature with insert enter didnt work for me :/

https://user-images.githubusercontent.com/59060246/128596426-7de373f5-2614-4cba-9eac-d9b532ec7a5f.mp4

**Comment by ashincoder** [comment]
check mine. it works for me

**Comment by ashincoder** [comment]
I will send a video

**Comment by ashincoder** [comment]
[asciicast](https://asciinema.org/a/zXoW0H7UVXdkG8ugKLFb2kQii)

**Comment by ashincoder** [comment]
It maybe ur problem. But it works fine for me

**Comment by ashincoder** [comment]
> @ashincoder you should test it before sending PR , lspsignature with insert enter didnt work for me :/
> 
>  simplescreenrecorder-2021-08-07_15.07.29.mp4

Do you really think I am that dumb to send a PR without testing :

**Comment by siduck76** [comment]
> > @ashincoder you should test it before sending PR , lspsignature with insert enter didnt work for me :/
> > simplescreenrecorder-2021-08-07_15.07.29.mp4
> 
> Do you really think I am that dumb to send a PR without testing :

doesnt work here , did you do packersync before after adding insertenter event?

**Comment by ashincoder** [comment]
yes. I did. I did packercompile also. 
I don't why but ok. If this works for you then ok

**Pull request merged**
