### PR TITLE
feat: added .ignore file

### PR DESCRIPTION
**Pull request by invisible1988**
Added .ignore file. So telescope doesn't ignore the custom folder.

### CODE REVIEW

**Comment by georgejean** [comment]
It would be nice to add your .ignore in .gitignore too (for possible additions of files/folders).

**Comment by georgejean** [comment]
Another option (I don't know if it works) would be to add .ignore in .gitignore to allow further possible file/folder additions.

**Comment by invisible1988** [comment]
Hi @georgejean,

do you mean removing the `.ignore` file and adding an exclusion for `.ignore` to `.gitignore`? So that any user could do it themselves? Or do you mean to keep the `.ignore` file and add it to `.gitignore`? So it would be shipped with the branch, but it would be possible to customise it?

Both would be possible....

**Comment by georgejean** [comment]
Hi @invisible1988.
I thought about the first option but if the second works, I think it's better (because of the included example).
I let @siduck give his opinion.

**Comment by invisible1988** [comment]
I think to ship a `.ignore` file would be good. But let's see what @siduck thinks. I'm fine with both.

**Comment by georgejean** [comment]
In fact I think the second option
> Or do you mean to keep the `.ignore` file and add it to `.gitignore`? So it would be shipped with the branch, but it would be possible to customise it?

wouldn't have downloaded the `.ignore` file with a `nvchadupdate` (because `.ignore` would be gitignored). Only fresh nvchad users would have this file (`git clone ...`). It's better now but it would be interesting to be able to add some of the other folder in `.gitignore` though.

**Pull request merged**
