### PR TITLE
Dev documentation

### PR DESCRIPTION
**Pull request by G-Rowell**
Hi all,

[Readme updates?](https://imgflip.com/i/5hq9q7)

[Demo](https://github.com/G-Rowell/NvChad/tree/dev-documentation)

tl;dr: monkies can install & readme easier

### CODE REVIEW

**Comment by siduck76** [comment]
I want to show the showcase first!! Beautiful screenshots is what would get anyone's attention for sure.

**Comment by G-Rowell** [comment]
I totally agree that the showcase is a big priority, and they do look beautiful
though I think there is big value to having a small bit of installation text near the top

Partly as it can show how easy it is to try out / get working

**Comment by siduck76** [comment]
> I totally agree that the showcase is a big priority, and they do look beautiful
> though I think there is big value to having a small bit of installation text near the top
> 
> Partly as it can show how easy it is to try out / get working

The links above it will work anyways

**Comment by siduck76** [comment]
image


less links look cool imo

**Comment by G-Rowell** [comment]
@siduck76, closing

I do think we need to revamp either the wiki or add a short installation section to the README, as the installation process is outdated.

Also need to think about a roadmap for the install script, I've read through many NVim config's and plenty of advanced ones automatically run Packer if it's needed.

**Comment by siduck76** [comment]
> @siduck76, closing
> 
> I do think we need to revamp either the wiki or add a short installation section to the README, as the installation process is outdated.
> 
> Also need to think about a roadmap for the install script, I've read through many NVim config's and plenty of advanced ones automatically run Packer if it's needed.

Do wikis support PRs?

**Comment by G-Rowell** [comment]
> > @siduck76, closing
> > I do think we need to revamp either the wiki or add a short installation section to the README, as the installation process is outdated.
> > Also need to think about a roadmap for the install script, I've read through many NVim config's and plenty of advanced ones automatically run Packer if it's needed.
> 
> Do wikis support PRs?

Yes, there is a GitHub repo setting where you can allow modifications. 
Currently you have the wiki set so only you can edit.

**Comment by G-Rowell** [comment]
https://stackoverflow.com/questions/48756517/github-public-wikis-option-will-it-give-access-to-write-to-any-github-user

https://github.community/t/repo-wiki-contributors/633

**Comment by siduck76** [comment]
> https://stackoverflow.com/questions/48756517/github-public-wikis-option-will-it-give-access-to-write-to-any-github-user
> 
> https://github.community/t/repo-wiki-contributors/633

Cool , I unticked the restrict wiki editing to collaborators only.

**Comment by G-Rowell** [comment]
Ahhhh, Ty Ty

I'd love to help improve the wiki but will focus on the then switcher rn

**Pull request closed without merging**
