### PR TITLE
fix: update init.lua to fix issues with incompatible bytecode

### PR DESCRIPTION
**Pull request by thisisjab**

### CODE REVIEW

**Comment by siduck** [comment]
which issues?

**Comment by thisisjab** [comment]
I tried using NvChad with neovim 0.10.0 and I faced errors related to line 19 of init.lua. Changing this line fixed the problem.

**Comment by siduck** [comment]
show your error please

**Comment by thisisjab** [comment]
`Error detected while processing /home/jab/.config/nvim/init.lua: E5113: Error while calling lua chunk: /home/jab/.local/share/nvim/nvchad/base46//defaults: cannot load incompatible bytecode stack traceback: [C]: in function 'dofile' /home/jab/.config/nvim/init.lua:19: in main chunk`

**Comment by siduck** [comment]
show me your chadrc

**Comment by thisisjab** [comment]
```---@type ChadrcConfig
local M = {}

-- Path to overriding theme and highlights files
local highlights = require "custom.highlights"

M.ui = {
  theme = "onedark",
  theme_toggle = { "onedark", "one_light" },

  hl_override = highlights.override,
  hl_add = highlights.add,
}

M.plugins = "custom.plugins"

-- check core.mappings for table structure
M.mappings = require "custom.mappings"

return M
```

**Comment by siduck** [comment]
show your   highlights

**Comment by thisisjab** [comment]
where can i find hightlights?

**Comment by BrunoKrugel** [comment]
> where can i find hightlights?

highlights.lua

**Comment by pookey** [comment]
Thanks - fixed a clean install on OSX:

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```


Edit: 

I think this could have been an issue for me as I'd moved a previous configuration out of the way before installing. Perhaps there's a cache somewhere I should have cleaned?   After having run the install, I was able to revert init.lua back to `dofile` and there was no longer the error while opening nvim.

**Comment by nolleh** [comment]
I am also have simillar issue, but after changed loadfile and then back to dofile, it works as fine.

**Comment by siduck** [comment]
https://github.com/NvChad/NvChad/assets/59060246/c5ec256e-ec06-4e5d-ad61-77a0c24a2470

i tried v0.10 but unable to reproduce this error

**Review by juniorsaldanha — COMMENTED** [review]
Thank for this PR, helped me to fix my first nvim startup on MacOS..

**Comment by siduck** [comment]
i'm unable to   reproduce this error!!!!! if you're using loadstring, then do know that there are dozens of places were dofile function is used

**Comment by siduck** [comment]
please make a video of clean nvchad installation + reproduce this  error, then'd it would be easy for me to debug

**Pull request closed without merging**
