### PR TITLE
add toggle terminal with lazygit config

### PR DESCRIPTION
**Pull request by curtainp**
substitute internal terminal to nvim-toggleterm.lua, which more cool. and add lazygit integration

### CODE REVIEW

**Comment by siduck76** [comment]
NvChad has basic functionality for spawning terminals horizontally / vertically . Any specific reason why does toggleterm needs to be added so it'd be helpful for most users

**Comment by curtainp** [comment]
toggleterm more effective when process background task, because of the identify terminal
``` lua 
-- in https://github.com/akinsho/nvim-toggleterm.lua/blob/master/lua/toggleterm/terminal.lua

--- get the toggle term number from
--- the name e.g. term://~/.dotfiles//3371887:/usr/bin/zsh;#toggleterm#1
--- the number in this case is 1
--- @param name string
--- @return number
function M.identify(name)
  name = name or api.nvim_buf_get_name(api.nvim_get_current_buf())
  local parts = vim.split(name, comment_sep)
  local id = tonumber(parts[#parts])
  return id, terminals[id]
end
```
and export a useful wrap class `Terminal` for extern program.

**Comment by siduck76** [comment]
@curtainp if you dont mind , could you fix the conflicts?

**Comment by G-Rowell** [comment]
@curtainp 
I think you've found a really good place we can improve, we'd love your input.

I'm leaning towards implementing this ourselves rn, but what do you think? anything to add?

**Comment by siduck76** [comment]
> So, there has been a good chat on the Discord about this!
> @curtainp
> 
> 
> It boils down to, this functionality is reasonably easy to implement ourselves, and there are plenty of valid reasons to go for the plugin & also to just write our own function.
> 
> I personally could go either way, after reading through the source code of https://github.com/akinsho/nvim-toggleterm.lua.
> 
> One thing to note, you mention `nvim-toggleterm.lua` is good for background tasks, we can easily replicate this functionality so it's not something that forces us to go with using `nvim-toggleterm.lua`

agreed , if there's not much hassle with implementing this easily from your side , then yea we wouldnt need the plugin!

**Comment by curtainp** [comment]
> So, there has been a good chat on the Discord about this!
> @curtainp
> 😄
> 
> It boils down to, this functionality is reasonably easy to implement ourselves, and there are plenty of valid reasons to go for the plugin & also to just write our own function.
> 
> I personally could go either way, after reading through the source code of [akinsho/nvim-toggleterm.lua](https://github.com/akinsho/nvim-toggleterm.lua).
> 
> One thing to note, you mention `nvim-toggleterm.lua` is good for background tasks, we can easily replicate this functionality so it's not something that forces us to go with using `nvim-toggleterm.lua`

yeah, agreed too.

**Comment by G-Rowell** [comment]
> > So, there has been a good chat on the Discord about this!
> > @curtainp
> > smile
> > It boils down to, this functionality is reasonably easy to implement ourselves, and there are plenty of valid reasons to go for the plugin & also to just write our own function.
> > I personally could go either way, after reading through the source code of [akinsho/nvim-toggleterm.lua](https://github.com/akinsho/nvim-toggleterm.lua).
> > One thing to note, you mention `nvim-toggleterm.lua` is good for background tasks, we can easily replicate this functionality so it's not something that forces us to go with using `nvim-toggleterm.lua`
> 
> yeah, agreed too.

Keep this open for now though!
We're still thinking/reading :)

**Comment by G-Rowell** [comment]
@curtainp Are you sonoMichele on Discord?

Also I've just realised this is your first PR ever!!!! Congrats!!!!!!!

**Comment by G-Rowell** [comment]
The more I've been investigating, the more I am starting to lean towards using the plugin, (for many reasons)

I'm more than happy to set it all up and make my own PR, though I want to offer you the chance (and not just take your project from you!)

Lemme know what you think, if you like you can reopen a new PR with these changes and we can chat there?

**Comment by curtainp** [comment]
> The more I've been investigating, the more I am starting to lean towards using the plugin, (for many reasons)
> 
> I'm more than happy to set it all up and make my own PR, though I want to offer you the chance (and not just take your project from you!)
> 
> Lemme know what you think, if you like you can reopen a new PR with these changes and we can chat there?

that‘s right, I will dig into the  terminal emulator of neovim as much as possible. it will be reopen when the awesome things finished.

**Comment by G-Rowell** [comment]
Oh damn, sorry! Only just saw this

@curtainp 

Check out my new PR, I think it follows NvChad's structure a little better

**Pull request closed without merging**
