### PR TITLE
Code style fixes | Some saner defaults

### PR DESCRIPTION
**Pull request by Akianonymus**

### CODE REVIEW

**Comment by siduck76** [comment]
@Akianonymus thanks! btw why do the icons look different? 

image

**Comment by siduck76** [comment]
looks like its using the default nvimtree config and not nvchad's

**Comment by Akianonymus** [comment]
> looks like its using the default nvimtree config and not nvchad's

I have pushed the fixes for that.

**Comment by Akianonymus** [comment]
btw @siduck76, why the folder name ( shows at top ) in nvim tree is hidden ? 

If are gonna say bufferline shows folder name, then the thing is that buffer doesn't appear when cursor is focused on tree.

**Comment by siduck76** [comment]
> btw @siduck76, why the folder name ( shows at top ) in nvim tree is hidden ?
> 
> If are gonna say bufferline shows folder name, then the thing is that buffer doesn't appear when cursor is focused on tree.

cuz the statusline already has the folder name

**Comment by Akianonymus** [comment]
@siduck76 As i said, statusline won't show when cursor is focused on file explorer.

**Comment by siduck76** [comment]
> @siduck76 As i said, statusline won't show when cursor is focused on file explorer.

cuz the statuslilne is made to be hidden when we focus on nvimtree!

**Comment by Akianonymus** [comment]
> > @siduck76 As i said, statusline won't show when cursor is focused on file explorer.
> 
> cuz the statuslilne is made to be hidden when we focus on nvimtree!

Then how is one supposed to see folder name when browsing file explorer

close file tree, see folder name in statusline ? totally pointless i think

**Comment by siduck76** [comment]
> > > @siduck76 As i said, statusline won't show when cursor is focused on file explorer.
> > 
> > 
> > cuz the statuslilne is made to be hidden when we focus on nvimtree!
> 
> i know that, ( the stuff in hideUtils )
> 
> Then how is one supposed to see folder name when browsing file explorer
> 
> close file tree, see folder name in statusline ? totally pointless i think

xd yea , the nvimtree rootdir looked ugly so i removed it

**Comment by siduck76** [comment]
@Akianonymus if we could have an underline of full length ( and not only the length of the folder's text ) then I'll add it back!

**Comment by Akianonymus** [comment]
> @Akianonymus if we could have an underline of full length ( and not only the length of the folder's text ) then I'll add it back!

I didn't understand, underline where ? ( i probably should see how it looks by default )

**Comment by siduck76** [comment]
> > @Akianonymus if we could have an underline of full length ( and not only the length of the folder's text ) then I'll add it back!
> 
> I didn't understand, underline where ? ( i probably should see how it looks by default )

oh sorry I missed the screenshot , here : 

image

**Comment by Akianonymus** [comment]
> > > @Akianonymus if we could have an underline of full length ( and not only the length of the folder's text ) then I'll add it back!
> > 
> > 
> > I didn't understand, underline where ? ( i probably should see how it looks by default )
> 
> oh sorry I missed the screenshot , here :
> 
> image

Underline or not, it really looks out of place there, even the position is not good i think.

**Comment by Akianonymus** [comment]
> > 
> > 
> > oh sorry I missed the screenshot , here :
> > image
> 
> Underline or not, it really looks out of place there, even the position is not good i think.

**Comment by siduck76** [comment]
@Akianonymus nvchad is now 10ms faster xd

image

now only two plugins arent lazy loaded , packer.nvim and nvim-base16.lua

**Comment by siduck76** [comment]
not much difference on ssd tho 

image

**Comment by Akianonymus** [comment]
> @Akianonymus nvchad is now 10ms faster xd
> 
> image
> 
> now only two plugins arent lazy loaded , packer.nvim and nvim-base16.lua

Config be like:
image

**Comment by Akianonymus** [comment]
> not much difference on ssd tho
> 
> image

SSDs are already ridiculously faster, what do you expect, xD

**Comment by siduck76** [comment]
> > not much difference on ssd tho
> > image
> 
> SSDs are already ridiculously faster, what do you expect, xD

Only stuff to lazy load is packer.nvim and the base16 plugin , I got tons of errors while lazy loading the base16 plugin tho ;( .maybe cuz bufferline , webdevicons and statusline plugins depend on it ( theme.lua for nvchad global theme var) .so loading base16 plugin first then the rest might work

**Comment by Akianonymus** [comment]
> > > not much difference on ssd tho
> > > image
> > 
> > 
> > SSDs are already ridiculously faster, what do you expect, xD
> 
> Only stuff to lazy load is packer.nvim and the base16 plugin , I got tons of errors while lazy loading the base16 plugin tho ;( .maybe cuz bufferline , webdevicons and statusline plugins depend on it ( theme.lua for nvchad global theme var) .so loading base16 plugin first then the rest might work

You can do theme.lua too, just define default theme variable first, although it does't look nice on opening files, thats why i didn't do it

because it will load theme after neovim startup, so it will show the base neovim theme for few milliseconds ( definitely visible to the eyes, will act like a flicker )

**Comment by siduck76** [comment]
@Akianonymus i have lazy loaded base16 plugin! no bugs so far and guess what? 10ms faster

image

**Comment by Akianonymus** [comment]
@siduck76 You do realize at this point it isn't getting faster, just hacking the benchmark.

Open a file or something, measure the time with a stopwatch or something, obviously it won't be 35 ms.

In my potato laptop, in real time, it takes like 1 sec to start ( to actually show the file i am opening, obviously nvim without any config opens instantly ).

About the base16, yes, it doesn't introduce a bug, i will send a screen record later.

**Comment by siduck76** [comment]
> @siduck76 You do realize at this point it isn't getting faster, just hacking the benchmark ( for slow machines ).
> 
> Open a file or something, measure the time with a stopwatch or something, obviously it won't be 35 ms.
> 
> In my potato laptop, in real time, it takes like 1 sec to start ( to actually show the file i am opening, obviously nvim without any config opens instantly ).
> 
> Because even if we send it to process asynchronously, it should have the power to actually carry out the task in the background.
> 
> About the base16, yes, it doesn't introduce a bug, i will send a screen record later.

how potato is your machine? mine has 1.6ghz pentium 4gb ram xD

**Comment by Akianonymus** [comment]
> > @siduck76 You do realize at this point it isn't getting faster, just hacking the benchmark ( for slow machines ).
> > Open a file or something, measure the time with a stopwatch or something, obviously it won't be 35 ms.
> > In my potato laptop, in real time, it takes like 1 sec to start ( to actually show the file i am opening, obviously nvim without any config opens instantly ).
> > Because even if we send it to process asynchronously, it should have the power to actually carry out the task in the background.
> > About the base16, yes, it doesn't introduce a bug, i will send a screen record later.
> 
> how potato is your machine? mine has 1.6ghz pentium 4gb ram xD

Mine is actually better than that, intel i3 4th gen ( 2.3 ghz ), but the hdd is so used up I can't explain.

Also, why isn't your pentium dead already ? xD

**Comment by siduck76** [comment]
idk it still works like a charm! GNU / Void linux rocks on it ! I prefer using it more than using my thinkpad with ssd xD

**Pull request merged**
