### PR TITLE
fix: fixed invalid index referencing in table due to user-specified i…

### PR DESCRIPTION
**Pull request by bozkayasalihx**
* its fixed "attempt to index a nil value" when used passed invalid configurations in his/her `custom/` directory

### CODE REVIEW

**Comment by siduck** [comment]
whats this? 
image

**Comment by bozkayasalihx** [comment]
@siduck, i assume i've accidentally created that file, I will remove it right now

**Comment by siduck** [comment]
and how do you reproduce the bug?

**Comment by bozkayasalihx** [comment]
@siduck, sure i was working on a golang project.  i did want to install dap for golang debuger but i didn't want to configure custom mapping for that just want to go with default configuration. after install dap plugin chadvim immediately threw `attempt to index nil value` in "core.utils.lua", i'll attach to ss for in case

Screenshot 2023-08-21 at 12 39 08
 
Screenshot 2023-08-21 at 12 44 07

but whenever i configured to dap plugin custom mapping. that error went away. here is my config
btw, this config is in `custom/mappings.lua`

Screenshot 2023-08-21 at 12 45 42

**Comment by siduck** [comment]
@bozkayasalihx you should format files using our stylua config btw

**Comment by bozkayasalihx** [comment]
@siduck, I thought i did. So yeah i've reformatted the files with stylua and committed too

**Comment by siduck** [comment]
can you share your mapping which causes this bug?

>  i didn't want to configure custom mapping for that just want to go with default configuration

btw you're supposed to add all your changes in custom dir only

**Comment by bozkayasalihx** [comment]
I already added, look at the screenshots and BTW I know where to put all of custom configuration but thanks for reminding

**Comment by siduck** [comment]
image

I added these mappings, i dont face any errors?

**Pull request closed without merging**
