### PR TITLE
Major perf improvements | Handle errors | Better configs | Misc 

### PR DESCRIPTION
**Pull request by Akianonymus**
install.sh: Don't ask for terminal shell when updating

---

[4/4] Refactor: install.sh: Don't handle packer | Misc

Handle a edgecase for config copying

---

[3/4] Refactor: init: Use async | Move theme stuff to theme.lua

third commit of refactor

perf improvements due to async

run packer sync if base16 not found

this is not perfect error handling for initial run, but something

handle require errors

---

[2/4] Refactor: plugins: Handle packer in seperate files | Handle packer cloning

second commit of refactor

handle require errors

handle cloning og packer

---

[1/4] Refactor: plugins: Add seperate config for each plugins

first commit of Refactor

handle require errors

move config from other places to proper files

---

Move options from init.lua => options.lua

use a local g = vim.g

---

Disable nvim intro and tilde chars on end of buffer

This avoids the situation when the initial screen looks out of place
because there is some pre rendered text

https://github.com/neovim/neovim/pull/8546

### CODE REVIEW

**Comment by Akianonymus** [comment]
Because of the large changes, i have splitted the commits for better readability.

Some bug may have slipped, so be sure to check everything.

**Comment by siduck76** [comment]
oh boii this looks a lot but I'll check it!

**Comment by siduck76** [comment]
btw what does async here mean? https://github.com/siduck76/NvChad/blob/c77496ab3aaebfcf43a61931c060ed2e541e25fb/init.lua 

ik only basic lua :c

**Comment by siduck76** [comment]
also what does this mean? 

image

**Comment by Akianonymus** [comment]
> btw what does async here mean? https://github.com/siduck76/NvChad/blob/c77496ab3aaebfcf43a61931c060ed2e541e25fb/init.lua
> 
> ik only basic lua , can you explain that part? :c

Async is a method in a programming language which we can use to do multiple things at once.

For example, packer.nvim, when we try to update the plugins or install, it doesn't fetch each plugin one by one, but fetch them all at once, thus decreasing the total amount of time taken.

Obviously, this isn't magic, it comes at a case of a increase cpu and ram utilisation, and only helps in cases when our machine can handle it.

Now, there are 4 other things

`vim.loop.new_async`: This a internal library function and as the name suggests, it is defining a new async process, which we can use ( just like a process )

`vim.schedule_wrap`: It waits until those statements inside are safe to call.

`async.close`: It will close the async process when all the tasks are complete.

`async.send`: It finally sends the async block to execute.

Now, when it does that, it doesn't keep nvim waiting and proceed to do next tasks, thus decreasing the initial startup time.

I  hope it was clear ( i am new to lua ).

**Comment by Akianonymus** [comment]
1

> what's pcall? can you explain this part? also why not just require("lspkind").init() ? it looks more cleaner!
> 
> image

Those are for handling errors in case lspkind is not available, like at first start-up.

pcall is an excellent exception handling method in lua which can handle almost every type of errors without adding much overhead to the total program ( it's negligible - the overhead ).

But yes, we can do that

```
local M = {}

M.config = function()
        pcall(
            function()
                 require("lspkind").init()
            end
        )
end

return M
```

It is splitting to new lines because lua-fmt is doing it, obviously not the required syntax.

**Comment by Akianonymus** [comment]
Btw, don't merge yet even if everything is fine, i have some local changes i gotta push.

**Comment by Akianonymus** [comment]
I have made some changes over the last one for code style for minimal final diffs.

And applied your suggestion too where possible while keeping it clean.

**Comment by siduck76** [comment]
> > what's pcall? can you explain this part? also why not just require("lspkind").init() ? it looks more cleaner!
> > image
> 
> Those are for handling errors in case lspkind is not available, like at first start-up.
> 
> pcall is an excellent exception handling method in lua which can handle almost every type of errors without adding much overhead to the total program ( it's negligible - the overhead ).
> 
> But yes, we can do that
> 
> ```
> local M = {}
> 
> M.config = function()
>         pcall(
>             function()
>                  require("lspkind").init()
>             end
>         )
> end
> 
> return M
> ```
> 
> It is splitting to new lines because lua-fmt is doing it, obviously not the required syntax.

Can you just use the require for all other plugin configs too? Honestly it looks much cleaner than defining variable and assigning it some value.

**Comment by siduck76** [comment]
@Akianonymus I get this error 

image

**Comment by siduck76** [comment]
lspconfig doesnt work too :( 

image

**Comment by Akianonymus** [comment]
> > > what's pcall? can you explain this part? also why not just require("lspkind").init() ? it looks more cleaner!
> > > image
> > 
> > 
> > Those are for handling errors in case lspkind is not available, like at first start-up.
> > pcall is an excellent exception handling method in lua which can handle almost every type of errors without adding much overhead to the total program ( it's negligible - the overhead ).
> > But yes, we can do that
> > ```
> > local M = {}
> > 
> > M.config = function()
> >         pcall(
> >             function()
> >                  require("lspkind").init()
> >             end
> >         )
> > end
> > 
> > return M
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It is splitting to new lines because lua-fmt is doing it, obviously not the required syntax.
> 
> Can you just use the require for all other plugin configs too? Honestly it looks much cleaner than defining variable and assigning it some value.

lmao what's wrong with using a variable ?

and the sole purpose i am doing it so I don't have to add everything inside the pcall function.

Beside that, it would add extra indentation to make it worse that it is right now.

Anyway, gotta fix the bugs first.

**Comment by siduck76** [comment]
the config is getting a lil complex tho! watchout

**Comment by Akianonymus** [comment]
Will try to fix those, i forgot to test i think.

About being complex, from the readme

```
PR's are always welcomed however NvChad aims to be less bloated and suckless.
```

Just doing that, xD

**Comment by siduck76** [comment]
> Will try to fix those, i forgot to test i think.
> 
> About being complex, from the readme
> 
> ```
> PR's are always welcomed however NvChad aims to be less bloated and suckless.
> ```
> 
> Just doing that, xD

yeah ik! those pcall/ async stuff scared me at first but looks ok now , anyways those errors are scary xD

**Comment by Akianonymus** [comment]
> > Will try to fix those, i forgot to test i think.
> > About being complex, from the readme
> > ```
> > PR's are always welcomed however NvChad aims to be less bloated and suckless.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Just doing that, xD
> 
> yeah ik! those pcall/ async stuff scared me at first but looks ok now , anyways those errors are scary xD

Well, that scary stuff will make this fast af, so worth it.

Thise errors will be fixed, just wrong a variable name in lspconfig  ( good thing pull requests exists ).

Before i make further changes, just had an idea

How about changing the plugins dir to configs, and in lua code we will just call

 ```
require "configs.statusline"
```

rather than

```
require "plugins.statusline".config()
```

**Comment by siduck76** [comment]
> > > Will try to fix those, i forgot to test i think.
> > > About being complex, from the readme
> > > ```
> > > PR's are always welcomed however NvChad aims to be less bloated and suckless.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Just doing that, xD
> > 
> > 
> > yeah ik! those pcall/ async stuff scared me at first but looks ok now , anyways those errors are scary xD
> 
> Well, that scary stuff will make this fast af, so worth it.
> 
> Thise errors will be fixed, just wrong a variable name in lspconfig ( good thing pull requests exists ).
> 
> Before i make further changes, just had an idea
> 
> How about changing the plugins dir to configs, and in lua code we will just call
> 
> ```
> require "configs.statusline"
> ```
> 
> rather than
> 
> ```
> require "plugins.statusline".config()
> ```

oh yeah this could be nice , so no config function required right? unwrap the plugin's ( statusline in this case ) config from the function

**Comment by Akianonymus** [comment]
> > 
> > 
> > Well, that scary stuff will make this fast af, so worth it.
> > Thise errors will be fixed, just wrong a variable name in lspconfig ( good thing pull requests exists ).
> > Before i make further changes, just had an idea
> > How about changing the plugins dir to configs, and in lua code we will just call
> > ```
> > require "configs.statusline"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > rather than
> > ```
> > require "plugins.statusline".config()
> > ```
> 
> oh yeah this could be nice , so no config function required right? unwrap the plugin's ( statusline in this case ) config from the function , just like bufferline has . also "plugins.statusline" looks better .

Yes, no function call to config, i can just return the config directly.
About "plugins.statusline" looking better, it sure does, i was just trying to make too much sense in the "configs.statusline".

**Comment by siduck76** [comment]
yeah update the PR , I'll test it :)

**Comment by Akianonymus** [comment]
> yeah update the PR , I'll test it :)

I have pushed some changes, test.

( still, don't merge it )

**Comment by siduck76** [comment]
yeah I'll do some changes , plugins having one liner configs / configs less than 6-7 ~ lines will be added in one single file.

**Comment by siduck76** [comment]
@Akianonymus can you send the PR in the dev branch? I'll merge it right away and refactor/change some stuff.

**Comment by siduck76** [comment]
is there any cleaner way of writing this? https://github.com/Akianonymus/NvChad/blob/main/lua/plugins/colorizer.lua

**Comment by Akianonymus** [comment]
> is there any cleaner way of writing this? https://github.com/Akianonymus/NvChad/blob/main/lua/plugins/colorizer.lua

Nope, maybe have to write a global function for pcall and use it

**Comment by Akianonymus** [comment]
> yeah I'll do some changes , plugins having one liner configs / configs less than 6-7 ~ lines will be added in one single file.

More complications, huh. Maybe a config.lua from where you can call.

**Comment by Akianonymus** [comment]
I think i should create a seperate pr for mergeable part of the pr.

**Comment by siduck76** [comment]
also btw why  

> I think i should create a seperate pr for mergeable part of the pr.

send the PR at the dev branch

**Comment by siduck76** [comment]
Btw @Akianonymus how do I use this without a function in other file??

```
local M = {}

M.neoscroll = function()
    pcall(
        function()
            require("neoscroll").setup()
        end
    )
end```

**Comment by Akianonymus** [comment]
> also btw why

This why was for ?

**Comment by siduck76** [comment]
> > also btw why
> 
> This why was for ?

nvm it , it was a typo lol

**Comment by Akianonymus** [comment]
Is this merge was a typo ? 😂 Because i am sure you said to create a different pr ( i was about to ).

All tested ? Hey, don't blame me it something borks heavily, xD

**Comment by siduck76** [comment]
> Is this merge was a typo ?  Because i am sure you said to create a different pr ( i was about to ).
> 
> All tested ? Hey, don't blame me it something borks heavily, xD

yeah I did tell that but then tested it several times here and there and got no errors. Ofc I'll ask for your help if something borks xd! Idk the async stuff . looks scary but works faster.

**Comment by Akianonymus** [comment]
> > Is this merge was a typo ?  Because i am sure you said to create a different pr ( i was about to ).
> > All tested ? Hey, don't blame me it something borks heavily, xD
> 
> yeah I did tell that but then tested it several times here and there and got no errors. Ofc I'll ask for your help if something borks xd! Idk the async stuff . looks ugly but works faster.

Well, as long as one runs PackerSync after the update, it should be fine.

I will probably push regarding that soon, to automatically sync missing stuff less errors as possible.

**Comment by Akianonymus** [comment]
On that note, i think there is too many tree sitters configured by default, it should be just bash and lua ( or maybe python, idk ). Definitely bloat i think ( html css and whatnot )

**Comment by siduck76** [comment]
> On that note, i think there are too many tree sitters configured by default, it should be just bash and lua ( or maybe python, idk ). Definitely bloat i think ( html css and whatnot )

yea I kept em for myself but yea its bloat for others so removed it!

**Comment by Akianonymus** [comment]
> > On that note, i think there are too many tree sitters configured by default, it should be just bash and lua ( or maybe python, idk ). Definitely bloat i think ( html css and whatnot )
> 
> yea I kept em for myself but yea its bloat for others so removed it!

Hmm, btw if you can, maybe you add a benchmark ss from a faster machine too.

**Comment by siduck76** [comment]
> > > On that note, i think there are too many tree sitters configured by default, it should be just bash and lua ( or maybe python, idk ). Definitely bloat i think ( html css and whatnot )
> > 
> > 
> > yea I kept em for myself but yea its bloat for others so removed it!
> 
> Hmm, btw if you can, maybe you add a benchmark ss from a faster machine too.

nvchad still slower than default neovim :((

image

(taken on my pentium machine)

**Comment by siduck76** [comment]
on my faster machine with ssd 

image

**Comment by Akianonymus** [comment]
> > > > On that note, i think there are too many tree sitters configured by default, it should be just bash and lua ( or maybe python, idk ). Definitely bloat i think ( html css and whatnot )
> > > 
> > > 
> > > yea I kept em for myself but yea its bloat for others so removed it!
> > 
> > 
> > Hmm, btw if you can, maybe you add a benchmark ss from a faster machine too.
> 
> nvchad still slower than default neovim :((
> 
> image
> 
> (taken on my pentium machine)

Haha, just 10 ms from unlimited power.

**Comment by Akianonymus** [comment]
> on my faster machine with ssd
> 
> image

Wow that is fast, ssd wonders i guess.

btw, a little offtopic, do you have your system configs pushed somewhere ? I would surely like to kang

**Comment by Akianonymus** [comment]
btw, by adding ss, I meant add to readme

**Comment by siduck76** [comment]
> btw, by adding ss, I meant add to readme

oh I will , also check my dotfiles repo ( thinkpad folder only) read its readme tho

**Pull request merged**
