### PR TITLE
- add 'nvim-osc52' plugin, support neovim clipboard and ssh copy.

### PR DESCRIPTION
**Pull request by ericwq**
`nvim-osc52` is a lua plugin, which support neovim clipboard and ssh remote copy.

clipboard support, check line 74-75
Screenshot 2023-05-22 at 10 29 24

yank multiple lines result, yank line  13~17, check the bottom message.
Screenshot 2023-05-22 at 10 28 59

### CODE REVIEW

**Comment by siduck** [comment]
@ericwq neovim clipboard support varies on different OS's , on linux it needs xclip or wl-clipboard package. You can just install that plugin in your custom plugins section

**Comment by ericwq** [comment]
> @ericwq neovim clipboard support varies on different OS's , on linux it needs xclip or wl-clipboard package. You can just install that plugin in your custom plugins section

osc52 is a ANSI OSC 52 sequence supported by terminal emulator. It doesn't need xclip or xsel. According to my test, kitty and alacritty both support this osc52 plugin. 

[Neovim 101 — OSC 52](https://alpha2phi.medium.com/neovim-101-osc-52-f4ee08fd96e6)

**Comment by siduck** [comment]
> > @ericwq neovim clipboard support varies on different OS's , on linux it needs xclip or wl-clipboard package. You can just install that plugin in your custom plugins section
> 
> osc52 is a ANSI OSC 52 sequence supported by terminal emulator. It doesn't need xclip or xsel. According to my test, kitty and alacritty both support this osc52 plugin.
> 
> [Neovim 101 — OSC 52](https://alpha2phi.medium.com/neovim-101-osc-52-f4ee08fd96e6)

oh didnt know, but still its limited to some terminals!

**Comment by ericwq** [comment]
OSC 52 is an ancient technology. Anyway I can use it as my custom plugin. Just want to share it with NvChad fans.

**Pull request closed without merging**
