### PR TITLE
Added logos and changed colors of readme

### PR DESCRIPTION
**Pull request by ashincoder**
Hello @siduck76 I made some changes in the readme.
I added logos.

### CODE REVIEW

**Comment by siduck76** [comment]
@ashincoder full black color doesnt look good , I meant the black in text color . this 

image

**Comment by siduck76** [comment]
the neovim icon looks good , but remove the black color and change it to defaults or use different colors . And remove the license logo too xD

**Comment by ashincoder** [comment]
hey @siduck76. Could you check the raw code of readme and change the colors according to your taste. I just made some changes for you to check

**Comment by ashincoder** [comment]
let the license logo be there it is the logo gnu license.

**Comment by ashincoder** [comment]
Preview here https://github.com/ashincoder/NvChad

**Comment by siduck76** [comment]
@ashincoder thank you so much! it looks much better now :D

image

**Comment by siduck76** [comment]
@ashincoder cant we have this lua badge's height the same as other badges? it looks a bit big

image

**Comment by ashincoder** [comment]
Actually that badge is meant to be big

**Comment by siduck76** [comment]
> Actually that badge is meant to be big

oh :l

**Comment by ashincoder** [comment]
Actually that badge is meant to be big

**Comment by ashincoder** [comment]
It isn't too bad.

**Comment by ashincoder** [comment]
It isn't too bad.

**Comment by siduck76** [comment]
> It isn't too bad.

Ik but I wanted to keep that logo below , with other logos but its a bit big so it wont match.

**Comment by ashincoder** [comment]
Actually it's not too bad

**Comment by ashincoder** [comment]
You can but change the widht of it with `logoWidth=`
but you can't change the height

**Comment by siduck76** [comment]
> You can but change the widht of it with `logoWidth=`
> but you can't change the height

oh nvm then , we'll just keep it the way it is.

**Pull request merged**
