### PR TITLE
added a option for custom footer in dashboard

### PR DESCRIPTION
**Pull request by ashincoder**

### CODE REVIEW

**Comment by siduck76** [comment]
we might have this if we find a way to disable statusline (galaxyline) from the dashboard footer.

image

**Comment by ashincoder** [comment]
but I don't have it.

**Comment by ashincoder** [comment]
The line which says the version

**Comment by siduck76** [comment]
> but I don't have it.



> but I don't have it.

I added it , and yea I found a way to disable the statusline :D

**Comment by ashincoder** [comment]
May be change the footer which you think is better and merge the PR

**Comment by siduck76** [comment]
> May be change the footer which you think is better and merge the PR

how does this look?

image

**Comment by ashincoder** [comment]
I don;t like the version number there.

**Comment by ashincoder** [comment]
Actually second thoughts let there version number be there. It looks great

**Comment by siduck76** [comment]
@ashincoder why closed the PR? I was about to add version in it and merge it!

**Comment by siduck76** [comment]
Nvm I'll add the changes now

**Pull request closed without merging**
