### PR TITLE
More comments and Edited Readme

### PR DESCRIPTION
**Pull request by ashincoder**
I added more comments for knowing.
I removed one screenshot.
I explained about Treesitter.

## TODO 
Change README and add:

- How to add custom plugins
- How to custom settings
- How to change themes.

### CODE REVIEW

**Comment by siduck76** [comment]
This feels unnecessary since those things dont need comments like 

require "statusline" already means adding statusline config and same with others .

**Comment by ashincoder** [comment]
It doesn't affect I added those lines just for continuity.

**Comment by ashincoder** [comment]
It is always better to add comments if not needed too. I mean it doesn't affect anyone.

**Comment by siduck76** [comment]
> It is always better to add comments if not needed too. I mean it doesn't affect anyone.

yes but our module are named better like pluginlist , anyone would get to know that its the moduleof plugins list, we dont have to write comments everywhere!

**Pull request closed without merging**
