### PR TITLE
Put non-lazy loaded lua files in a top-level runtime folder (plugin) instead of using require

### PR DESCRIPTION
**Pull request by shaunsingh**
fixes https://github.com/siduck76/NvChad/issues/175

So far I've moved everything except the `theme.lua` and `plugins.bufferline.lua`, both were giving me errors. I left them async loaded for now.

### CODE REVIEW

**Comment by shaunsingh** [comment]
image

Before on top, after on bottom

**Comment by JustSage** [comment]
Are the highlights working properly for you ? once made this change the colors are off.

**Comment by siduck76** [comment]
@shaunsingh @Akianonymus whats the dstore binary file?

**Comment by Akianonymus** [comment]
@siduck76 Lol i don't have a clue.

**Comment by siduck76** [comment]
> @siduck76 Lol i don't have a clue.

yeah I hope it isnt system specific , how was the bin file even created tho o.O

**Comment by Akianonymus** [comment]
@siduck76

From Wikipedia

```
DS_Store is a file that stores custom attributes of its containing folder, such as the position of icons or the choice of a background image. The name is an abbreviation of Desktop Services Store, reflecting its purpose.
Developed by: Apple Inc
```

**Comment by siduck76** [comment]
> @siduck76
> 
> From Wikipedia
> 
> ```
> DS_Store is a file that stores custom attributes of its containing folder, such as the position of icons or the choice of a background image. The name is an abbreviation of Desktop Services Store, reflecting its purpose.
> Developed by: Apple Inc
> ```

I tested this PR and here : 

image

:worried:

**Comment by siduck76** [comment]
also mappings dont work D:

**Comment by Akianonymus** [comment]
> > @siduck76
> > From Wikipedia
> > ```
> > DS_Store is a file that stores custom attributes of its containing folder, such as the position of icons or the choice of a background image. The name is an abbreviation of Desktop Services Store, reflecting its purpose.
> > Developed by: Apple Inc
> > ```
> 
> I tested this PR and here :
> 
> image ( it was 17~ before xd)
> 
> 😟

Try hyperfine, it will do worse there too, i don't he got improvement doing these changes.

**Comment by siduck76** [comment]
> > I tested this PR and here :
> > image ( it was 17~ before xd)
> > worried
> 
> Try hyperfine, it will do worse there too, i don't know he got improvement doing these changes.

i did , it got slower :c 

before vs after 

image

**Comment by Akianonymus** [comment]
> > > I tested this PR and here :
> > > image ( it was 17~ before xd)
> > > worried
> > 
> > 
> > Try hyperfine, it will do worse there too, i don't know he got improvement doing these changes.
> 
> i did , it got slower :c
> 
> with pr vs without pr
> 
> image

Yep yep yep.

**Comment by siduck76** [comment]
oof! why doesnt the mappings config work? @shaunsingh any idea?

**Comment by siduck76** [comment]
I think nvchad is already at its peak in speed lol , only thing that feels needed at this moment is a theme switcher , maybe creating a picker with telescope would help a lot

**Comment by Akianonymus** [comment]
I have created the pr: https://github.com/siduck76/NvChad/pull/180

**Comment by siduck76** [comment]
> I have created the pr: #180

oof I liked the low startuptime xD, but nvm!

**Comment by Akianonymus** [comment]
> > I have created the pr: #180
> 
> oof I liked the low startuptime xD, but nvm!

It is just an illusion, if you really wanna check, use a stopwatch, not joking, i literally did 😂.

**Comment by siduck76** [comment]
> > > I have created the pr: #180
> > 
> > 
> > oof I liked the low startuptime xD, but nvm!
> 
> It is just an illusion, if you really wanna check, use a stopwatch, not joking, i literally did .

yeah Im aware but nvim ui loaded faster with async tho :p

**Pull request closed without merging**
