### PR TITLE
Siduck76 main

### PR DESCRIPTION
**Pull request by MOHENOO**

### CODE REVIEW

**Comment by siduck76** [comment]
bruh read the contribute section!

**Comment by MOHENOO** [comment]
I'm sorry. This is not my intention. I'm new of github.But i fount \<Tab\> key not support lussnip.Maybe It should be
```lua
 _G.tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-n>"
    elseif require("luasnip").expand_or_jumpable() then
        return t "<cmd>lua require'luasnip'.jump(1)<Cr>"
    elseif check_back_space() then
        return t "<Tab>"
    else
        return vim.fn["compe#complete"]()
    end
end

_G.s_tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-p>"
    elseif require("luasnip").jumpable(-1) then
        return t "<cmd>lua require'luasnip'.jump(-1)<CR>"
    else
        return t "<S-Tab>"
    end
end
```
in mappings.lua. It works fine. 
[luasnip's issue](https://github.com/L3MON4D3/LuaSnip/issues/1)

**Comment by siduck76** [comment]
@MOHENOO no worries! btw what does this do? Im confused.

**Comment by MOHENOO** [comment]
jump to prev/next snippet's placeholder when use luasnip.

**Comment by siduck76** [comment]
> jump to prev/next snippet's placeholder when use luasnip.

could you show a demo of it?

**Comment by MOHENOO** [comment]
like this:
demo

**Comment by siduck76** [comment]
> like this:
> demo

Oh you mean that pop-up on the right which shows the snippets content?

**Comment by MOHENOO** [comment]
no,before i type main,when i choice snippet, i can pass \<tab\> jump to next snippet's placeholder,\<S-tab\> jump to prev.

**Comment by MOHENOO** [comment]
Sorry🥺, english isn't my mother language. Maybe i didn't explain clearly enough.

**Comment by siduck76** [comment]
you mean this as placeholder?

image

**Comment by MOHENOO** [comment]
no, that's different.please look.
#### Use origin config
```lua
_G.tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-n>"
    elseif check_back_space() then
        return t "<Tab>"
    else
        return vim.fn["compe#complete"]()
    end
end

_G.s_tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-p>"
    elseif vim.fn.call("vsnip#jumpable", {-1}) == 1 then
        return t "<Plug>(vsnip-jump-prev)"
    else
        return t "<S-Tab>"
    end
end
```

after i expand snippet, i pass \<tab\> .it input tab,not move next placeholder like this

origin.

#### Use my config
```lua
_G.tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-n>"
    elseif require("luasnip").expand_or_jumpable() then
        return t "<cmd>lua require'luasnip'.jump(1)<Cr>"
    elseif check_back_space() then
        return t "<Tab>"
    else
        return vim.fn["compe#complete"]()
    end
end

_G.s_tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-p>"
    elseif require("luasnip").jumpable(-1) then
        return t "<cmd>lua require'luasnip'.jump(-1)<CR>"
    else
        return t "<S-Tab>"
    end
end
```
after i expand snippet, i pass \<tab\> ,it move next placeholder like this
my'config

**Pull request closed without merging**
