### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Akianonymus**

### CODE REVIEW

**Comment by siduck76** [comment]
The theme name should stay in the theme.lua , shouldnt get separated from it!

**Comment by Akianonymus** [comment]
@siduck76 How about this, it will remain in theme.lua, but a fallback theme name in options.lua, just in case for first install ( ik, too much for first install, but it is what it is ).

**Comment by siduck76** [comment]
> @siduck76 How about this, it will remain in theme.lua, but a fallback theme name in options.lua, just in case for first install ( ik, too much for first install, but it is what it is ).

i dont think its needed for first install . just add dark bg for NormalFloat cuz it looks light pink during the first install xd

**Comment by Akianonymus** [comment]
@siduck76 Well, i will remove the theme stuff for now, gotta figure out something else.

**Review by siduck76 — APPROVED** [review]

**Pull request merged**
