### PR TITLE
nicer feline default config

### PR DESCRIPTION
**Pull request by FelixKratz**
Screen Shot 2022-05-09 at 20 54 47
Removes some duplicate information and cleaner code.

### CODE REVIEW

**Comment by LeonHeidelbach** [comment]
I would second this change :smile: This seems to be a lot cleaner.

**Comment by siduck** [comment]
@FelixKratz thanks for the PR but I think our current statusline looks better and different

**Comment by GreatestOfAllTimee** [comment]
> Screen Shot 2022-05-09 at 20 54 47
> 
> Removes some duplicate information and cleaner code.

Personally this are much better than current Nvchad statusline.

**Comment by GreatestOfAllTimee** [comment]
> > Screen Shot 2022-05-09 at 20 54 47
> > Removes some duplicate information and cleaner code.
> 
> Personally this are much cleaner than current Nvchad statusline.

**Comment by FelixKratz** [comment]
The current statusline is very unorganised (git icons and branch on other sides, lsp icon and errors/warnings on different sides) and the file title is duplicate when you have tabline also enabled. For those that want to use my adapted feline anyways: https://github.com/FelixKratz/dotfiles/tree/master/.config/nvim/lua/custom

**Comment by siduck** [comment]
Yes I'm aware that it's unorganized but you didn't had to change the mode towards left , otherwise it looked good. I'll make up the shortcomings soon

**Comment by LeonHeidelbach** [comment]
> Yes I'm aware that it's unorganized but you didn't had to change the vi mode towards left , otherwise it looked good. I'll make up the shortcomings soon

It has actually always been the default to show the mode on the lower left though, so it would be more in line with how it is natively set up.

image

leaving `vim.opt.showmode = true` is kinda unnecessary if you have the mode displayed in feline.

**Comment by GreatestOfAllTimee** [comment]
> Yes I'm aware that it's unorganized but you didn't had to change the vi mode towards left , otherwise it looked good. I'll make up the shortcomings soon

Why dont you just rework on this PR rather than close and make a separate PR?

> It has actually always been the default to show the mode on the lower left though, so it would be more in line with how it is natively set up.

Yes that sounds reasonable. Display things twice is not necessary

**Comment by siduck** [comment]
> Why dont you just rework on this PR rather than close and make a separate PR?
 
i would have to revert this change as well then 
image


Also I wont accept new PR's for statusline at the moment, I will add new components in it. You'll know at v2.0 gigachad release

**Comment by LeonHeidelbach** [comment]
@siduck do you have a rough ETA on 2.0 yet? Is it gonna have a lot of breaking changes?

**Comment by siduck** [comment]
> @siduck do you have a rough ETA on 2.0 yet? Is it gonna have a lot of breaking changes?

no breaking changes , We might have only 1 breaking change and that would be this https://github.com/NvChad/NvChad/issues/1047

I'll simplify changing mappings :)

**Comment by siduck** [comment]
Im thinking of having a domain (as it would look  more polished and less basic) but the domain's costly and I cant invest in it while being broke  :laughing:

**Comment by LeonHeidelbach** [comment]
> > @siduck do you have a rough ETA on 2.0 yet? Is it gonna have a lot of breaking changes?
> 
> 
> 
> no breaking changes , We might have only 1 breaking change and that would be this https://github.com/NvChad/NvChad/issues/1047
> 
> 
> 
> I'll simplify changing mappings :)

Sounds good. Yeah I saw that, simplifying the way to change default mappings is definitely a good idea 👍🏻 

> Also Im thinking of having a domain for the site (as it would look  more polished and less basic after v2.0) but the domain's costly and I cant invest in it whilst being broke  :laughing: 
> 
> 
> 
> https://domains.google.com/registrar/search?searchTerm=nvchad&utm_source=google&utm_medium=cpc&hl=en&_ga=2.251510723.415272488.1652178907-953805741.1652178907

Dude no-one cares about a domain as long as the product is well crafted… so don't put too high of a priority on that.

**Comment by siduck** [comment]
> > > @siduck do you have a rough ETA on 2.0 yet? Is it gonna have a lot of breaking changes?
> > 
> > 
> > no breaking changes , We might have only 1 breaking change and that would be this #1047
> > I'll simplify changing mappings :)
> 
> Sounds good. Yeah I saw that, simplifying the way to change default mappings is definitely a good idea 👍🏻
> 
> > Also Im thinking of having a domain for the site (as it would look  more polished and less basic after v2.0) but the domain's costly and I cant invest in it whilst being broke  laughing
> > https://domains.google.com/registrar/search?searchTerm=nvchad&utm_source=google&utm_medium=cpc&hl=en&_ga=2.251510723.415272488.1652178907-953805741.1652178907
> 
> Dude no-one cares about a domain as long as the product is well crafted… so don't put too high of a priority on that.

yep a thought came to me that it'd be bloated to type nvchad.github.io than nvchad.com but then I realized it'd be waste of money over a trivial thing like a domain

**Comment by LeonHeidelbach** [comment]
Yeah, I mean this is a website for an open source project and not a corporate homepage, so no need to be fancy with the URL. Maybe if you get enough sponsors and the thing pays for itself but if that's not the case, don't bother.

**Comment by GreatestOfAllTimee** [comment]
Can I know the meaning of **_‘release’_** in Nvchad? Correct me if I'm wrong, Nvchad installation is directly from the `main` branch which means there is no specific development branch or release branch/source. So technically unstable and stable features all in one branch, it doesn't seem very useful for Nvchad to announce incoming releases.

**Comment by siduck** [comment]
mega , giga , tera and so on. 

the first release was named megachad and the upcoming is gigachad

**Comment by GreatestOfAllTimee** [comment]
> nvchad will get stable after v2.0

so that's mean nvchad doesn't really care about mixing stable and unstable commit?

**Comment by siduck** [comment]
you can easily do a packersnapshot for a stable backup ,check the docs

**Comment by FelixKratz** [comment]
Could we have a ChadSnapshot that saves the current commit has of the chad repo and additionally creates a PackerSnapshot. It could then be possible to do a ChadRevert to the last known good version. Could also be nice to do this automatically on <leader>uu and if something is bricked afterwards we could do ChadRevert to get back to the state before <leader>uu? Possibly @LeonHeidelbach?

**Comment by GreatestOfAllTimee** [comment]
> you can easily do a packersnapshot for a stable backup ,check the docs

Yes I know, it's completely different. If nvchad is included with a separate developer and release branch users will not have to face any broken changes before v2.0 will be released. Recently we faced 2 breaking changes in 2 months.

**Comment by GreatestOfAllTimee** [comment]
> > you can easily do a packersnapshot for a stable backup ,check the docs
> 
> Yes I know, it's completely different. If nvchad is included with a separate developer and release branch users will not have to face any breaking changes before v2.0 will be released (`<leader>uu` everything will messed up). Recently we faced 2 breaking changes in 2 months.

**Comment by siduck** [comment]
ik its annoying @GreatestOfAllTimee , breaking changes occur when syntax changes of custom stuff become "easy" , I do  it for yall! But you wont have breaking changes after v2.0, pinky promise!

**Comment by siduck** [comment]
I agree with you @LeonHeidelbach , Do as you please and make it better. im kinda noobish with git stuff so cant help with it xd

**Comment by LeonHeidelbach** [comment]
@siduck Alright, I will look into it and do some git magic 😆

**Comment by GreatestOfAllTimee** [comment]
Don't get me wrong, this is just my opinion. You should not promise, we do not know whats will come on neovim side _(features)_ maybe it will bring something useful for nvchad _(it might cause a breaking changes)_.

Breaking changes is normal, but breaking changes 2-4 times in a month are something we need to avoid. So my comment above are my suggestion how nvchad should manage stable & unstable commit.

**Comment by GreatestOfAllTimee** [comment]
especially for user who dont want to deal with this kind of things. Configure vim/neovim config really take sometimes to get it right even tho their using vim/neovim for a decade

**Comment by siduck** [comment]
> Don't get me wrong, this is just my opinion. You should not promise, we do not know whats will come on neovim side _(features)_ maybe it will bring something useful for nvchad _(it might cause a breaking changes)_.
> 
> Breaking changes is normal, but breaking changes 2-4 times in a month are something we need to avoid. So my comment above are my suggestion how nvchad should manage stable & unstable commit.

agreed, I take back my promise

**Comment by siduck** [comment]
currently one upcoming breaking change regarding changing mappings, i will simplify it

**Pull request closed without merging**
