### PR TITLE
Add theme: Dracula

### PR DESCRIPTION
**Pull request by Iorvethe**
This adds the Dracula colorscheme as described [here](https://spec.draculatheme.com/).

## Screenshot

Screenshot_20210810_131900

Related issue: #225

### CODE REVIEW

**Comment by JustSage** [comment]
Seems legit, well done :)

**Comment by siduck76** [comment]
Black2 must be 6% lighter than black

**Comment by Akianonymus** [comment]
> Black2 must be 6% lighter than black

where are the docs for this magic info ?

**Comment by Iorvethe** [comment]
> Black2 must be 6% lighter than black

Made it lighter. Better?

**Comment by Iorvethe** [comment]
#225

**Comment by siduck76** [comment]
> > Black2 must be 6% lighter than black
> 
> where are the docs for this magic info ?

The wiki section for making nvchad themes mentions how to search which color is being used by which highlight.  In this case black2 is used by mostly bufferline bg , in all other themes you can see the bufferline bg color lool lighter than Normal guibg , anyways o will improve the theme wiki soon.

**Comment by siduck76** [comment]
> > Black2 must be 6% lighter than black
> 
> Is it better now?

I will test it after getting home , also you need to add  a better syntax theme for it in nvim-base16.lua repo.

**Comment by Iorvethe** [comment]
> > > Black2 must be 6% lighter than black
> > 
> > 
> > Is it better now?
> 
> I will test it after getting home , also you need to add a better syntax theme for it in nvim-base16.lua repo.

That's right. Will do it today. Thanks for merging this part!

**Comment by Iorvethe** [comment]
It appears that thanks to @Akianonymus's [MR](https://github.com/siduck76/nvim-base16.lua/pull/3), it's already in that repo. 

I tried it and it's already very nice. If you're good with it, I'll leave it as is.

**Comment by siduck76** [comment]
> It appears that thanks to @Akianonymus's [MR](https://github.com/siduck76/nvim-base16.lua/pull/3), it's already in that repo.
> 
> If you're good with it, I'll leave it as is.

its using weird colors so im gonna change them

**Comment by Iorvethe** [comment]
Alright, thanks for taking care of that.

**Comment by siduck76** [comment]
@Iorvethe which one looks good? 
 
 
image

**Comment by Iorvethe** [comment]
In my opinion, the right one is better, but not by much. Both are quite good. But since the right one is more faithful to the original theme, I think we should stick with it. The users choosing the Dracula theme will be expecting it.

I saw that you wanted to make another Dracula-inspired theme. Maybe you can use the left version for it?

Just a remark regarding it. The parentheses shouldn't have such a catchy color. They aren't the most important part of the code and thus should be less visible, more neutral.

And again, thanks for your efforts!

**Comment by siduck76** [comment]
> In my opinion, the right one is better, but not by much. Both are quite good. But since the right one is more faithful to the original theme, I think we should stick with it. The users choosing the Dracula theme will be expecting it.
> 
> I saw that you wanted to make another Dracula-inspired theme. Maybe you can use the left version for it?
> 
> Just a remark regarding it. The parentheses shouldn't have such a catchy color. They aren't the most important part of the code and thus should be less visible, more neutral.
> 
> And again, thanks for your efforts!

yeah the left version is used now and I wanted to make a better version of dracula tbh

**Comment by siduck76** [comment]
some screenshots 
imageimage
image

**Pull request merged**
