### PR TITLE
Init: Home manager module and Devshell

### PR DESCRIPTION
**Pull request by YvesStraten**
This PR aims at adding a home manager module for NvChad and a devShell, adding 2 files:
- `flake.nix`
- `default.nix`

### CODE REVIEW

**Comment by orhnk** [comment]
Why did you opted `home.file.".config"` instead you could use `xdg.configFile`?

Isn't that platform specific (e.g for WSL)

**Comment by YvesStraten** [comment]
@orhnk, no it is not platform bound, it is a part of home manager. Any person who has a home manager installation in their flake or channel based installation has access to these methods.

As to why I used it, I used it to be able to symlink folders easily with the `recursive = true` arg

**Comment by siduck** [comment]
@javacafe01

**Comment by chxp82q** [comment]
@YvesStraten You should consider using `xdg.configFile`, as the way you are currently using `home.file` implys that the config directory is always `~/.config`.

No specific target is needed and the files are placed relative to the config directory, wherever it's set.

**Comment by YvesStraten** [comment]
Alright, does it support recursive symlinking? I can't seem to find much documentation about it

**Comment by YvesStraten** [comment]
Alright, I will switch this to a `xdg.configFile` implementation

**Comment by siduck** [comment]
@YvesStraten wasnt it decided that this'd be in a separate repo? :thinking:

**Comment by YvesStraten** [comment]
No, I was told that I should make a Pr here by you and @orhnk if I am not mistaken, and that you would decide on this later down the line. If I remember right, you were still deciding whether you wanted to change the code % bar eyecandy

**Comment by YvesStraten** [comment]
I am open to do this in another repo, nontheless

**Comment by siduck** [comment]
https://github.com/NvChad/nix send PR there @YvesStraten

**Comment by siduck** [comment]
send PR there @YvesStraten

**Comment by YvesStraten** [comment]
Alright

**Pull request closed without merging**
