### PR TITLE
Introduced fixes and certain features from master branch to stable re…

### PR DESCRIPTION
**Pull request by tashrifsanil**
## Notes:

- Added keybindings from master branch such as toggle file tree to stable release
- Added back dashboard
- Got rid of startup errors with telescope and indent-blankline

This might not be worth merging as some work might be ongoing on the master branch, but it does fix issues that come in the stable release. The only changes this pull request adds from the master branch to the stable branch are changes to fix start up errors, and to add back the slick dashboard.

### CODE REVIEW

**Comment by ashincoder** [comment]
I don't think @siduck76 will merge this.

**Comment by siduck76** [comment]
> ## Notes:
> * Added keybindings from master branch such as toggle file tree to stable release
> * Added back dashboard
> * Got rid of startup errors with telescope and indent-blankline
> 
> This might not be worth merging as some work might be ongoing on the master branch, but it does fix issues that come in the stable release. The only changes this pull request adds from the master branch to the stable branch are changes to fix start up errors, and to add back the slick dashboard.

dashboard is just off by default , https://github.com/siduck76/NvChad/wiki#dashboard . I dont think we should enable it by default.

**Comment by siduck76** [comment]
also what startup errors? the config from master branch is working fine af. Also you removed all of the lazy loading features :(

**Comment by siduck76** [comment]
I will create a stable branch when the v1.0 release is ready.

**Comment by tashrifsanil** [comment]
Yeahh I'm still a noob when it comes to vim and lua script, so I just spliced together the config files to get rid of the errors. I think my issues were Gentoo specific, because it'd pull in an older version of neovim, and won't build with luajit.

And it actually seems like there are no errors, and the errors I saw came from trying to get dashboard working on the master branch. I do apologize about that!

Lastly honestly good job so far, this is by far the sickest vim setup I've seen and can't wait to see what comes from it. I'll go ahead and close this pull request!

**Comment by siduck76** [comment]
@tashrifsanil I suggest you learning some of the basic nvim lua stuff  in your free time so you'll understand the config better and its really very worth it. 

https://github.com/siduck76/NvChad/wiki/Lua-guides

**Pull request closed without merging**
