### PR TITLE
feat(cmp): Make words from opened buffers available in autocomplete snippet for faster coding.

### PR DESCRIPTION
**Pull request by obieewan**
I prefer working on open buffer and contents available in autocomplete in vim. This option will make the same feature available.

-Obie

### CODE REVIEW

**Comment by siduck** [comment]
@obieewan you can simple override cmp sources in your custom plugins table.

**Comment by obieewan** [comment]
Okay got it thanks. It is my first time setting up neovim. :) I had issue implement this in custom plugins, conflicts with other snippets. Tailwind and html snips not working.

**Comment by siduck** [comment]
@obieewan  make sure you write entire sources table.

```lua
sources = {
     { name = "buffer",
      option = {
        get_bufnrs = function()
          return vim.api.nvim_list_bufs()
        end
      }
    },
    { name = "nvim_lsp"  },
    { name = "path" },
    { name = "luasnip" },
    { name = "nvim_lua" },
  }
  ```

**Comment by obieewan** [comment]
Thank you, finally it's working.

**Pull request closed without merging**
