### PR TITLE
Remove placebo async stuff | Replace startuptime plugin with actually working one | Do not load packer

### PR DESCRIPTION
**Pull request by Akianonymus**

### CODE REVIEW

**Comment by siduck76** [comment]
image

why is treesitter sourced -.-?

**Comment by Akianonymus** [comment]
> image
> 
> why is treesitter sourced -.-?

Nothing to do with this pr, remove the last two commits ( keeping the startuptime commit ) and it will be same.

**Comment by siduck76** [comment]
> > image
> > why is treesitter sourced -.-?
> 
> Nothing to do with this pr, remove the last two commits ( keeping the startuptime commit ) and it will be same.

how does it check startuptime?  startuptime.vim didnt show treesitter or such

**Comment by Akianonymus** [comment]
> > > image
> > > why is treesitter sourced -.-?
> > 
> > 
> > Nothing to do with this pr, remove the last two commits ( keeping the startuptime commit ) and it will be same.
> 
> how does it check startuptime? startuptime.vim didnt show treesitter or such

It just shows sourced stuff by default. Use --no-sourcing-stuff to not see it. But doesn't matter anyway.

**Comment by siduck76** [comment]
> > > Nothing to do with this pr, remove the last two commits ( keeping the startuptime commit ) and it will be same.
> > 
> > 
> > how does it check startuptime? startuptime.vim didnt show treesitter or such
> 
> It just shows sourced stuff by default. Use --no-sourcing-stuff to not see it. But doesn't matter anyway.

is there any option to sum up the startuptime?

**Comment by Akianonymus** [comment]
> > > > Nothing to do with this pr, remove the last two commits ( keeping the startuptime commit ) and it will be same.
> > > 
> > > 
> > > how does it check startuptime? startuptime.vim didnt show treesitter or such
> > 
> > 
> > It just shows sourced stuff by default. Use --no-sourcing-stuff to not see it. But doesn't matter anyway.
> 
> is there any option to sum up the startuptime?

Probably not i think, have to see.

**Comment by Akianonymus** [comment]
Seems like a issue is there, https://github.com/dstein64/vim-startuptime/issues/6

Maybe i will pr there, lol ( if i succesful in doing so ).

**Comment by Akianonymus** [comment]
Actually, @siduck76, if you do Shift+k on top bar ( where is shows event and stuff, it shows total time ).

**Comment by siduck76** [comment]
> Actually, @siduck76, if you do Shift+k on top bar ( where is shows event and stuff, it shows total time ).

image

**Comment by siduck76** [comment]
> Actually, @siduck76, if you do Shift+k on top bar ( where is shows event and stuff, it shows total time ).

how much do you get?

**Comment by Akianonymus** [comment]
> > Actually, @siduck76, if you do Shift+k on top bar ( where is shows event and stuff, it shows total time ).
> 
> how much do you get?

Potato machine
image

Non potato machine
image

**Comment by Akianonymus** [comment]
Actually, this is actual on my potato laptop
image

Seems like it lagged just after i started my laptop

**Comment by siduck76** [comment]
> > > Actually, @siduck76, if you do Shift+k on top bar ( where is shows event and stuff, it shows total time ).
> > 
> > 
> > how much do you get?
> 
> Potato machine
> image
> 
> Non potato machine
> image

yeah i get 250~ on potato and 83~ on ssd , i dont find any slowness , btw does this sums up treesitter and not sourced plugins too?

**Comment by Akianonymus** [comment]
> yeah i get 250~ on potato and 83~ on ssd , i dont find any slowness , btw does this sums up treesitter and not sourced plugins too?

See my updated ss

Also, it includes i think. See `:h StartupTime`

**Comment by ashincoder** [comment]
I knew the async stuff was just a placebo

**Comment by Akianonymus** [comment]
@ashincoder Should have told us, haha.

anyway, i am fool for not researching much and blindly believing on some dummy stats.

**Comment by siduck76** [comment]
> @ashincoder Should have told us, haha.
> 
> anyway, i am fool for not researching much and blindly believing on some dummy stats.

its ok mate , I would still want to use the *async* stuff in the private xD. I like seeing too less startuptime lol

**Comment by ashincoder** [comment]
Hey @Akianonymus I told you in the telegram right didn't I.

**Comment by ashincoder** [comment]
Sorry @siduck76 I should have said to you that. But I think I have said it so @Akianonymus . Anyway I have implemented async in StarVim. Cause why not. Even though it may not affect the time it is still like a show off xD.

**Comment by siduck76** [comment]
> Sorry @siduck76 I should have said to you that. But I think I have said it so @Akianonymus . Anyway I have implemented async in StarVim. Cause why not. Even though it may not affect the time it is still like a show off xD.

yeah I liked its syntax a lot too lul but it does nothing and most nvim users gonna hate us for using it lol , it makes nvim ui load faster tho

**Comment by Akianonymus** [comment]
@ashincoder Nope, you said it didn't showed any difference on benchmark for you, but it did for me.

**Comment by ashincoder** [comment]
Yeah :

**Pull request merged**
